[package]
name = "piccolo"
version = "0.1.1"
description = "Stackless Lua VM implemented in pure Rust"
authors = ["kyren <catherine@kyju.org>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/kyren/piccolo"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
allocator-api2 = "0.2"
anyhow = "1.0"
gc-arena = { git = "https://github.com/kyren/gc-arena", features = ["allocator-api2", "hashbrown"] }
hashbrown = { version = "0.14", features = ["raw"] }
rand = { version = "0.8", features = ["small_rng"] }
rustc-hash = "1.1"
thiserror = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
clap = { version = "4.3", features = ["cargo"] }
rustyline = "11.0"
